# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-20 10:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blog_author'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'verbose_name': '\u0411\u043b\u043e\u0433', 'verbose_name_plural': '\u0411\u043b\u043e\u0433\u0438'},
        ),
    ]
