# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-28 13:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0006_post_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='f',
            field=models.FileField(default='', upload_to=b''),
            preserve_default=False,
        ),
    ]
