# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-20 14:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20160420_1034'),
        ('post', '0008_auto_20160420_1034'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='blog',
        ),
        migrations.AddField(
            model_name='post',
            name='blog',
            field=models.ManyToManyField(related_name='posts', to='blog.Blog', verbose_name='\u0411\u043b\u043e\u0433'),
        ),
    ]
